version: '3.9'
services:

  api:
    build:
      context: .
      dockerfile: deploy/docker/general/Dockerfile
    command: "api"
    ports:
      - "${API_HTTP_LOCAL_PORT:-8082}:${API_HTTP_PORT:-80}"
    restart: always
    env_file: ".env"

    extra_hosts:
      - "host.docker.internal:host-gateway"


  cron:
    build:
      context: .
      dockerfile: deploy/docker/general/Dockerfile
    command: "cron"
    restart: always
    env_file: ".env"
    extra_hosts:
      - "host.docker.internal:host-gateway"
